//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace euroPlus4_1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string sqlServerConfig {
            get {
                return ((string)(this["sqlServerConfig"]));
            }
            set {
                this["sqlServerConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5432")]
        public int sqlPortConfig {
            get {
                return ((int)(this["sqlPortConfig"]));
            }
            set {
                this["sqlPortConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string sqlUserIdConfig {
            get {
                return ((string)(this["sqlUserIdConfig"]));
            }
            set {
                this["sqlUserIdConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191260")]
        public string sqlPasswordConfig {
            get {
                return ((string)(this["sqlPasswordConfig"]));
            }
            set {
                this["sqlPasswordConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sysEP4")]
        public string sqlDataBase {
            get {
                return ((string)(this["sqlDataBase"]));
            }
            set {
                this["sqlDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\Documents")]
        public string CaminhoLog {
            get {
                return ((string)(this["CaminhoLog"]));
            }
            set {
                this["CaminhoLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string C_NomeDaMaquina {
            get {
                return ((string)(this["C_NomeDaMaquina"]));
            }
            set {
                this["C_NomeDaMaquina"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string C_PosicaoNaPlanta {
            get {
                return ((string)(this["C_PosicaoNaPlanta"]));
            }
            set {
                this["C_PosicaoNaPlanta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string C_NumeroDeSerie {
            get {
                return ((string)(this["C_NumeroDeSerie"]));
            }
            set {
                this["C_NumeroDeSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_TensaoDeEntrada {
            get {
                return ((int)(this["C_TensaoDeEntrada"]));
            }
            set {
                this["C_TensaoDeEntrada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string C_Fabricante {
            get {
                return ((string)(this["C_Fabricante"]));
            }
            set {
                this["C_Fabricante"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/0001")]
        public string C_AnoDeFabricacao {
            get {
                return ((string)(this["C_AnoDeFabricacao"]));
            }
            set {
                this["C_AnoDeFabricacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_TipoDeAplicacao {
            get {
                return ((int)(this["C_TipoDeAplicacao"]));
            }
            set {
                this["C_TipoDeAplicacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool C_MostrarNome {
            get {
                return ((bool)(this["C_MostrarNome"]));
            }
            set {
                this["C_MostrarNome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_Tema {
            get {
                return ((int)(this["C_Tema"]));
            }
            set {
                this["C_Tema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_CorDeDestaque {
            get {
                return ((int)(this["C_CorDeDestaque"]));
            }
            set {
                this["C_CorDeDestaque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool C_AplicarModo {
            get {
                return ((bool)(this["C_AplicarModo"]));
            }
            set {
                this["C_AplicarModo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00")]
        public string C_HoraInicial {
            get {
                return ((string)(this["C_HoraInicial"]));
            }
            set {
                this["C_HoraInicial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00")]
        public string C_HoraFinal {
            get {
                return ((string)(this["C_HoraFinal"]));
            }
            set {
                this["C_HoraFinal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_ProtocoloEthernet {
            get {
                return ((int)(this["C_ProtocoloEthernet"]));
            }
            set {
                this["C_ProtocoloEthernet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string C_EnderecoIp {
            get {
                return ((string)(this["C_EnderecoIp"]));
            }
            set {
                this["C_EnderecoIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("801")]
        public int C_Porta {
            get {
                return ((int)(this["C_Porta"]));
            }
            set {
                this["C_Porta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_ProtocoloSerial {
            get {
                return ((int)(this["C_ProtocoloSerial"]));
            }
            set {
                this["C_ProtocoloSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_BaudRate {
            get {
                return ((int)(this["C_BaudRate"]));
            }
            set {
                this["C_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_StopBit {
            get {
                return ((int)(this["C_StopBit"]));
            }
            set {
                this["C_StopBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_Paridade {
            get {
                return ((int)(this["C_Paridade"]));
            }
            set {
                this["C_Paridade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int C_NumeroEstacao {
            get {
                return ((int)(this["C_NumeroEstacao"]));
            }
            set {
                this["C_NumeroEstacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sqlTipoBancoSelecionado {
            get {
                return ((int)(this["sqlTipoBancoSelecionado"]));
            }
            set {
                this["sqlTipoBancoSelecionado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sysEPcontrol")]
        public string UsuarioMaster {
            get {
                return ((string)(this["UsuarioMaster"]));
            }
            set {
                this["UsuarioMaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mastercontrol191260")]
        public string SenhaMaster {
            get {
                return ((string)(this["SenhaMaster"]));
            }
            set {
                this["SenhaMaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int C_TempoLeituraEthernet {
            get {
                return ((int)(this["C_TempoLeituraEthernet"]));
            }
            set {
                this["C_TempoLeituraEthernet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MPa")]
        public string C_UnidadePressao {
            get {
                return ((string)(this["C_UnidadePressao"]));
            }
            set {
                this["C_UnidadePressao"] = value;
            }
        }
    }
}
